### ISSUE TITLE
Upgrade to embedded-graphics to 0.7

### ISSUE THREAD

**Issue by jamwaffles** [yuri91/ili9341-rs#27]
I could be missing something here, but it shouldn't be necessary to implement integrations for both embedded-graphics and embedded-graphics-core - the intent with the crate split in e-g 0.7 is that only the latter is required.

Are both implementations in the crate to support older versions of e-g perhaps?

**Comment by jamwaffles** [comment]
Oh, I just found https://github.com/yuri91/ili9341-rs/pull/26#issuecomment-840666446. I'll rename this ticket!

**Comment by yuri91** [comment]
Yes, the plan is to support only 0.7 not that it is out. I will do it this weekend probably

**Comment by yuri91** [comment]
I removed support for embedded-graphics 0.6.x.
I also bumped the version to 0.5.0 and pushed it to crates.io

**Comment by jamwaffles** [comment]
Awesome! Great to see the new version being used :)
