### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Disasm** [yuri91/ili9341-rs#9]
Since #7 and #8 have landed, do you mind releasing a new version of this crate?

**Comment by yuri91** [comment]
Yeah, a new release makes sense, but I was waiting for embedded-graphics to release 0.6 (https://github.com/jamwaffles/embedded-graphics/projects/6), since right now we depend on 0.6.0-alpha.2.

Maybe I should release an alpha version as well?

**Comment by jamwaffles** [comment]
We release [0.6.0-beta.1](https://crates.io/crates/embedded-graphics/0.6.0-beta.1) a few days ago. I guess you could release a beta of this crate?

Assuming nothing major comes up, there should be no more breaking changes before the release of 0.6.0 proper.

**Comment by yuri91** [comment]
Seems reasonable to me. I will try to update to 0.6.0-beta.1 of embedded-graphics and then release a 0.3.0-beta.1 of this crate to crates.io

**Comment by jamwaffles** [comment]
Sounds good to me. That's what I've been doing with SSD1306 etc

**Comment by yuri91** [comment]
I just implemented the new embedded_graphics interface and published 0.3.0-beta.1 on crates.io!

Let me know if there are issues!

**Comment by Disasm** [comment]
Thank you!
